SSHOPT="-o userknownhostsfile=/dev/null -o StrictHostKeyChecking=no"

shopt -s autocd

alias ssh="/usr/bin/ssh $SSHOPT"
alias ta="tmux -2 a"
alias vi="nvim"
alias l="ls -lF"
alias s="ls -F"
alias u="cd .."
alias h="cd ~"
alias b="cd -"
alias gp="git push"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"
alias sb="source. ~/dotfiles/bashrc"
alias tal="sudo tail -300f /var/log/apache2/error.log"
alias p3="ssh pi3"
alias pf="ssh flypi"
